include all tests 
//1 GIVEN A LIST OF NUMBERS, WRITE A PYTHON FUNCTION USING MAP() THAT SQAUERES EACH NUMBER IN THE LIST.
Numbers=[1,2,3,4,5]

Output:[1,4,9,16,25]


#2
#WRITE A PYTHON FUNCTION THAT CONVERTS A LIST OF STRINGS TO THEIR CORRESPONDING LENGTHS USING MAP() FUNCTION


#words=["apple", "banana","cherry"]
#output:[5,6]
